parameters:
  windowsPool: VSEng-MicroBuildVS2019
  macPool: MicroBuildV2MacPool

jobs:
- job: Windows

  variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: _TeamName
    value:  Emblazon

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - name: _BuildArgs
      value: /p:TeamName=$(_TeamName)
    - name: _SignType
      value: real

  - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    - name: _BuildArgs
      value: ''
    - name: _SignType
      value: test
    - name: _PublishArgs
      value: ''

  pool: ${{ parameters.windowsPool }}
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud'
    displayName: Set build number

  - template: dotnet.yml

# NOTE: This is disabled due to https://github.com/dotnet/Nerdbank.GitVersioning/issues/487
# - job: macOS
#   pool: ${{ parameters.macPool }}
#   steps:
#   - checkout: self
#     clean: true
#   - template: install-dependencies.yml
#     parameters:
#       initArgs: -NoRestore # Mac build restores its own projects so that Windows-only projects can be excluded
#   - template: dotnet-mac.yml

- job: WrapUp
  dependsOn:
  - Windows
#  - macOS
  pool: ${{ parameters.windowsPool }}
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-deployables.yml
